# Generated by Django 5.1.15 on 2026-09-21 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base gross amount', max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g. 10.00 for 10%)', max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=18.0, help_text='GST / Tax percentage (default 18.00%)', max_digits=5)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_status', models.BooleanField(default=False)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient')),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
    ]
