# Generated by Django 5.1.15 on 2026-09-21 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicines', models.JSONField(default=list, help_text='List of medicines with name, dosage, frequency, and duration')),
                ('dosage', models.CharField(help_text='Summary dosage regimen', max_length=200)),
                ('instructions', models.TextField(blank=True, default='Take after meals. Maintain adequate hydration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
